apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: app-taken 
  janus-idp.io/tekton: app-taken
  backstage.io/kubernetes-id: app-taken
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: app-taken
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  